name: Deploy

on: 
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-22.04.2

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Deploy via SSH
      uses: appleboy/ssh-action@developmet
      with:
        host: '103.59.95.40'
        username: 'ijul'
        script: | 
          cd ~/app/library-app-api
          docker-compose down
          git pull origin development
          cd keys
          rm mongo-replica-set.key
          openssl rand -base64 741 > mongo-replica-set.key
          sudo chmod 600 mongo-replica-set.key
          cd ..
          docker-compose up -d